system:
  data_dir: "./data"
  allowed_formats: [".csv", ".xlsx"]

models:
  xgboost:
    learning_rate: 0.1
    max_depth: 6
    scale_pos_weight: "auto"
    eval_metric: "aucpr"
    early_stopping_rounds: 10
